package springcore_day1;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Main {
	private static ApplicationContext context;
	
	public static void main(String[] args) {
		context = new ClassPathXmlApplicationContext("beans.xml");
		//Properties are set by setter method
		HelloBean bean1 = (HelloBean) context.getBean("helloBean");
		bean1.sayHello();
		HelloBean beanb = (HelloBean) context.getBean("helloBean");
		//Generated by singleton
		System.out.println(bean1);
		System.out.println(beanb);
		//Properties are set by a Constructor with parameter
		HelloBean2 bean2 = (HelloBean2) context.getBean("helloBean2");
		bean2.sayHello();
		HelloBean2 bean2b = (HelloBean2) context.getBean("helloBean2");
		//Generated by prototype
		System.out.println(bean2);
		System.out.println(bean2b);
		
		UserService userService = (UserService) context.getBean("userService");
		userService.printInfo();
		
		Person person = (Person) context.getBean("person");
		person.printInfo();
		
		Person2 person2 = (Person2) context.getBean("person2");
		person2.printComplex();
	}
}
